### ISSUE TITLE
 [!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (...ZDCChatAPI.framework and ...ZDCChat.framework)

### ISSUE THREAD

**Issue by AndreyTCR** [emostar/flutter-zendesk#1]
**After install from pub to my project have that error:**
 [!] The 'Pods-Runner' target has transitive dependencies that include static binaries: (...ZDCChatAPI.framework and ...ZDCChat.framework)
 /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/xcode/target_validator.rb:81:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:443:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/installer.rb:124:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.0.beta.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

-------------------------------

**But example project works fine**

**Comment by andreidiaconu** [comment]
Same error on my side. I should mention my project is a Swift project - and I think this is related to https://github.com/flutter/flutter/issues/14161

@emostar What do you think adding `s.static_framework = true` to the podspecs file would fix this?

**Comment by andreidiaconu** [comment]
Tried it on my own fork and it works fine. Not sure if it messes things up for Objective-C project but I expect it doesn't. Cheers.

**Comment by emostar** [comment]
Thanks for the PR!

**Comment by andreidiaconu** [comment]
You should also consider releasing a new version `1.0.1` to pub.dev, otherwise people can't easilly use the library with the fix. Thank you.

**Comment by emostar** [comment]
Just did. Thanks for the feedback!
