### ISSUE TITLE
Customize UI

### ISSUE THREAD

**Issue by antonino-tocco** [emostar/flutter-zendesk#10]
Hi, it is possible to customize ui?

I want to change appbar color, message style etc...

Can you help me?

**Comment by xiaozihao92** [comment]
https://developer.zendesk.com/embeddables/docs/android-chat-sdk/customization

**Comment by zeucxb** [comment]
@antonino-tocco @xiaozihao92 Do you have some sample customizing it in a flutter project?

**Comment by emostar** [comment]
You would need to customize each platform individually based on the documentation from zendesk. @xiaozihao92 posted the link for the Android style changes. You would just need to look in your 'android/' folder and modify it like a normal Android app. Same for iOS, but under the 'ios/' folder.
