### ISSUE TITLE
The parameter of init() method should be account key

### ISSUE THREAD

**Issue by crizant** [emostar/flutter-zendesk#2]
From the example, you used a variable named `ZendeskApiKey`, which is very misleading.
The correct parameter is Zendesk account key, which is a total different thing.

**Comment by agenthighcastle** [comment]
> From the example, you used a variable named `ZendeskApiKey`, which is very misleading.
> The correct parameter is Zendesk account key, which is a total different thing.

JESUS, thank you! This fixed my issue.
And yeah, please fix this.

**Comment by emostar** [comment]
Thanks for the feedback. It was called the API Key when they were Zopim... I updated it to reflect the naming conventions used for Zendesk.
