### ISSUE TITLE
Keyboard overflowing input

### ISSUE THREAD

**Issue by zeucxb** [emostar/flutter-zendesk#8]
Keyboard overflowing input on chat

**Comment by dwayne-roadhouse** [comment]
If this is relating to the keyboard overlapping the edittext, I am having the same issue

**Comment by emostar** [comment]
Can someone share a screenshot of what it looks like?

I have a feeling that it is a problem with the zendesk SDK directly and not much we can do, but a screenshot would help me see what is going on.

**Comment by dwayne-roadhouse** [comment]
Hopefully these will help
![itemtwo](https://user-images.githubusercontent.com/62041683/78314088-9d28bb00-75a4-11ea-9a5e-ff243d9fff1d.png)
![itemone](https://user-images.githubusercontent.com/62041683/78314093-a023ab80-75a4-11ea-885f-8f77fa84f96a.png)

**Comment by dwayne-roadhouse** [comment]
This doesn't appear to happen in a native app, though the SDK version may be different.

![File](https://user-images.githubusercontent.com/62041683/78317765-e978f880-75ae-11ea-9ffb-eb151a14bf71.jpg)

**Comment by dwayne-roadhouse** [comment]
Just an update on this, it appears that the master branch fixes this problem. Looks like @emostar was correct and it was an issue with the ZenDesk SDK.

**Comment by zeucxb** [comment]
@emostar 
"ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs" is probably also from the ZenDesk SDK, right?

**Comment by emostar** [comment]
@dwayne-roadhouse I'm glad you got the issue resolved by updating Zendesk SDK!

**Comment by emostar** [comment]
@zeucxb The latest versions of Zendesk SDK have that removed. If you are using Firebase flutter libraries, they had that issue too. I'm not getting that warning from Apple after updating all my dependencies to their latest release versions.

I'm going to go ahead and close this, as the keyboard issue is resolved by updating the zendesk SDK.

**Comment by bhargavsejpalindianic** [comment]
> @dwayne-roadhouse I'm glad you got the issue resolved by updating Zendesk SDK!

How to update ?

**Comment by dwayne-roadhouse** [comment]
The master branch currently has the updated SDK, so you can specify the master branch instead of a version, or wait for a new version to be released. 

My suggestion is to fork this library for now so that future updates to master do not break your app. At least until an update is released. 

You can do that by using the following pubspec entry

zendesk:
    git: '<Your fork URL>'

**Comment by bhanuka96** [comment]
> The master branch currently has the updated SDK, so you can specify the master branch instead of a version, or wait for a new version to be released.
> 
> My suggestion is to fork this library for now so that future updates to master do not break your app. At least until an update is released.
> 
> You can do that by using the following pubspec entry
> 
> zendesk:
>   git: 'Your fork URL'

I got the same issue.

Is it fix when change like this?

pubspec.yaml

```
  zendesk:
    git: 'https://github.com/emostar/flutter-zendesk.git'
```

**Comment by dwayne-roadhouse** [comment]
Try
`  
zendesk:
    git: 'https://github.com/roadhouse-dev/flutter-zendesk.git'
`

That's all we are using, but it looks like it's just a fork of this repository.

If this does work for you, please make your own fork as there's no guarantee that we won't remove it later.
